name: "Setup Git"
description: "A composite action to setup Git config"
inputs:
  user_name:
    description: "Set a user name"
    default: "github-actions[bot]"
    required: false
  user_email:
    description: "Set a user email"
    default: "github-actions[bot]@users.noreply.github.com"
    required: false
  working_directory:
    description: "Set a working directory"
    default: ""
    required: false
runs:
  using: "composite"
  steps:
    - name: "git config"
      shell: "bash"
      working-directory: "${{ inputs.working_directory }}"
      run: |
        git config user.name "${{ inputs.user_name }}"
        git config user.email "${{ inputs.user_email }}"
