name: "Setup Hugo"
description: "A composite action to setup Hugo project."
inputs:
  node-version:
    description: "Set a Node.js version, e.g. 16.14.2"
    default: "16"
    required: false
  go-version:
    description: "Set a Go version, e.g. 1.18"
    required: false
  go-version-file:
    description: "Set a path to the go.mod, e.g. path/to/go.mod"
    default: "go.mod"
    required: false
  hugo-version:
    description: "Set a Hugo version, e.g. 0.97.3"
    default: "latest"
    required: false
  extended:
    description: "Download and use Hugo extended version, if necessary. e.g. true"
    default: "false"
    required: false
  cache-path:
    description: "The path input of actions/cache"
    default: |
      /tmp/hugo_cache
      ~/go/pkg/mod
      ~/.npm
    required: false
  cache-key:
    description: "The key input of actions/cache"
    default: "${{ runner.os }}-hugo-${{ hashFiles('**/go.sum') }}-${{ hashFiles('**/package-lock.json') }}"
    required: false
  cache-restore-keys:
    description: "The restore-keys input of actions/cache"
    default: "${{ runner.os }}-hugo-"
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version: "${{ inputs.go-version }}"
        go-version-file: "${{ inputs.go-version-file }}"

    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: "${{ inputs.node-version }}"

    - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: "${{ inputs.cache-path }}"
        key: "${{ inputs.cache-key }}"
        restore-keys: "${{ inputs.cache-restore-keys }}"

    - run: npm i -g npm
      shell: bash

    - uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: "${{ inputs.hugo-version }}"
        extended: "${{ inputs.extended }}"
