name: 'Setup Node.js'
description: 'A composite action to setup Node.js project.'
inputs:
  node-version:
    description: 'Set a Node.js version, e.g. 18.16.0'
    required: false
  node-version-file:
    description: 'File containing the version Spec of the version to use.  Examples: .nvmrc, .node-version, .tool-versions'
    required: false
  cache:
    description: 'Used to specify a package manager for caching in the default directory. Supported values: npm, yarn, pnpm.'
    required: false
    default: 'npm'
runs:
  using: "composite"
  steps:
    - run: npm install -g corepack && corepack enable npm pnpm yarn
      shell: bash

    - uses: actions/setup-node@v3.7.0 # https://github.com/actions/setup-node/releases
      with:
        node-version: '${{ inputs.node-version }}'
        node-version-file: '${{ inputs.node-version-file }}'
        cache: '${{ inputs.cache }}'
