name: 'Setup Node.js'
description: 'A composite action to setup Node.js project.'
inputs:
  node-version:
    description: 'Set a Node.js version, e.g. 16.14.2'
    default: '16'
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '${{ inputs.node-version }}'

    - uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - run: npm i -g npm
      shell: bash
