name: 'Create release for npm'
description: 'Create release for npm'
inputs:
  draft:
    description: 'Enable --draft flag'
    default: '--draft'
    required: false
  prerelease:
    description: 'Enable --prerelease flag'
    default: '--prerelease'
    required: false
runs:
  using: "composite"
  steps:
    - name: Create release
      run: |
        TAG_NAME="${GITHUB_REF##refs/tags/}"
        echo "See [CHANGELOG.md](https://github.com/${GITHUB_REPOSITORY}/blob/${TAG_NAME}/CHANGELOG.md) for more details." > ./release_notes.md
        RELEASE_TITLE="$(jq -r '.name' ./package.json) ${TAG_NAME}"
        gh release create "${TAG_NAME}" ${{ inputs.draft }} ${{ inputs.prerelease }} \
          --title "${RELEASE_TITLE}" \
          --notes-file ./release_notes.md
      shell: bash
