name: "Setup Go"
description: "A composite action to setup Go project."
inputs:
  go-version:
    description: "Set a Go version, e.g. 1.19"
    required: false
  go-version-file:
    description: "Set a path to the go.mod, e.g. path/to/go.mod"
    default: "go.mod"
    required: false
  cache-path:
    description: "The path input of actions/cache"
    default: "~/go/pkg/mod"
    required: false
  cache-key:
    description: "The key input of actions/cache"
    default: "${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}"
    required: false
  cache-restore-keys:
    description: "The restore-keys input of actions/cache"
    default: |
      ${{ runner.os }}-go-
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
      with:
        go-version: "${{ inputs.go-version }}"
        go-version-file: "${{ inputs.go-version-file }}"

    - uses: peaceiris/workflows/setup-mage@v0.21.2
    - uses: peaceiris/workflows/setup-goreleaser@v0.21.2

    - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: "${{ inputs.cache-path }}"
        key: "${{ inputs.cache-key }}"
        restore-keys: "${{ inputs.cache-restore-keys }}"
