name: "Setup Go"
description: "A composite action to setup Go project."
inputs:
  go-version:
    description: "Set a Go version, e.g. 1.19"
    required: false
  go-version-file:
    description: "Set a path to the go.mod, e.g. path/to/go.mod"
    default: "go.mod"
    required: false
  cache-path:
    description: "The path input of actions/cache"
    default: "~/go/pkg/mod"
    required: false
  cache-key:
    description: "The key input of actions/cache"
    default: "${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}"
    required: false
  cache-restore-keys:
    description: "The restore-keys input of actions/cache"
    default: |
      ${{ runner.os }}-go-
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
      with:
        go-version: "${{ inputs.go-version }}"
        go-version-file: "${{ inputs.go-version-file }}"

    - uses: peaceiris/workflows/setup-mage@v0.21.0
    - uses: peaceiris/workflows/setup-goreleaser@v0.21.0

    - uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
      with:
        path: "${{ inputs.cache-path }}"
        key: "${{ inputs.cache-key }}"
        restore-keys: "${{ inputs.cache-restore-keys }}"
