name: 'Setup Python'
description: 'A composite action to setup Python project.'
inputs:
  python-version:
    description: 'Set a Python version, e.g. 3.8'
    default: '3.8'
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}

    - uses: actions/cache@v2
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

    - run: python3 -m pip install --upgrade pip pipenv
      shell: bash
