name: 'Setup Python'
description: 'A composite action to setup Python project.'
inputs:
  python-version:
    description: 'Set a Python version, e.g. 3.10.3'
    default: '3.10'
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: ${{ inputs.python-version }}

    - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

    - run: python3 -m pip install --upgrade pip pipenv
      shell: bash
