name: 'Setup Python'
description: 'A composite action to setup Python project.'
inputs:
  python-version:
    description: 'Set a Python version, e.g. 3.10.3'
    default: '3.10'
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
      with:
        python-version: ${{ inputs.python-version }}

    - uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

    - run: python3 -m pip install --upgrade pip pipenv
      shell: bash
