name: 'Install github/hub'
description: 'Install github/hub'
inputs:
  placeholder:
    description: 'placeholder'
    default: ''
    required: false
runs:
  using: "composite"
  steps: 
    - name: Install github/hub
      run: |
        export HUB_VERSION="2.14.2"
        curl -fsSL https://github.com/github/hub/raw/8d91904208171b013f9a9d1175f4ab39068db047/script/get | bash -s "${HUB_VERSION}"
      shell: bash
    - run: hub version
      shell: bash
