name: Lint Workflows

# https://github.com/rhysd/actionlint

on:
  workflow_call:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/*.ya?ml'
  pull_request:
    paths:
      - '.github/workflows/*.ya?ml'

jobs:
  actionlint:
    runs-on: ubuntu-22.04
    timeout-minutes: 1
    permissions:
      contents: read
    concurrency:
      group: "${{ github.workflow }}-${{ github.ref }}"
      cancel-in-progress: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - uses: docker://rhysd/actionlint:1.7.0
        with:
          args: -color
