name: Lint Workflows

# https://github.com/rhysd/actionlint

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/*'
  pull_request:
    paths:
      - '.github/workflows/*'

jobs:
  actionlint:
    runs-on: ubuntu-22.04
    timeout-minutes: 1
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - uses: docker://rhysd/actionlint:1.7.0
        with:
          args: -color
