name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  lint:
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Validate renovate.json
        run: npx --package renovate -c 'renovate-config-validator'

  setup-docker:
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: ./setup-docker
      - run: docker version
      - run: docker compose version
      - run: docker buildx version
