name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  setup-docker:
    runs-on: ubuntu-24.04
    timeout-minutes: 3
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./setup-docker
      - run: docker version
      - run: docker compose version
      - run: docker buildx version
