name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  lint:
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: peaceiris/workflows/setup-node@v0.19.1
        with:
          node-version-file: '.nvmrc'
      - run: npm ci
      - run: npm test

  setup-docker:
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: ./setup-docker
      - run: docker version
      - run: docker compose version
      - run: docker buildx version
