name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  setup-docker:
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: ./setup-docker
      - run: docker version
      - run: docker compose version
      - run: docker buildx version
