name: hadolint

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-24.04
    container:
      image: 'hadolint/hadolint:v2.12.0-alpine'
    timeout-minutes: 5
    permissions:
      contents: read
    concurrency:
      group: "${{ github.workflow }}-${{ github.ref }}"
      cancel-in-progress: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v4
      - name: Lint Dockerfile
        run: |
          find . -type f -name "Dockerfile" -exec dirname {} \; | while read -r d; do
            (cd "${d}" && hadolint Dockerfile)
          done
