name: hadolint

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-22.04
    container:
      image: 'hadolint/hadolint:v2.12.0-alpine'
    permissions:
      contents: read
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Lint Dockerfile
        run: |
          find . -type f -name "Dockerfile" -exec dirname {} \; | while read -r d; do
            (cd "${d}" && hadolint Dockerfile)
          done
