name: Release

run-name: "Release: ${{ github.event.inputs.semver_type }} version"

on:
  workflow_dispatch:
    inputs:
      semver_type:
        description: "Semver type"
        required: true
        type: "choice"
        options:
          - "patch"
          - "minor"
          # - "major"
        default: "minor"

jobs:
  main:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - uses: peaceiris/workflows/setup-node@v0.21.2
        with:
          node-version-file: '.nvmrc'

      - uses: peaceiris/workflows/setup-git@v0.21.2

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          CURRENT_TAG=$(git describe --abbrev=0 --tags)
          NEW_VERSION=$(npm_config_yes=true npx semver "${CURRENT_TAG}" --increment ${{ github.event.inputs.semver_type }})
          NEW_TAG="v${NEW_VERSION}"
          RELEASE_TITLE="peaceiris/workflows ${NEW_TAG}"
          git tag -a "${NEW_TAG}" -m "${RELEASE_TITLE}"
          git push origin "${NEW_TAG}"
          gh release create "${NEW_TAG}" --title "${RELEASE_TITLE}" --generate-notes
